
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbhqwnlzjsmuhqufwzhb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRiaHF3bmx6anNtdWhxdWZ3emhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyOTA1MDMsImV4cCI6MjA1Nzg2NjUwM30.2CIaGr6QD4ebUP89dZAvZJuSf10EGYrSDO5Gx6FXZ7Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
